import { Button, AboutSlint } from "std-widgets.slint";
import { I18n } from "i18n.slint";

export component AboutDialog inherits Dialog {
    width: 400px;
    height: 300px;
    title: I18n.about-title;
    icon: @image-url("icon/about.png");
    always-on-top: false;
    no-frame: false;

    VerticalLayout {
        alignment: center;
        spacing: 10px;
        Text {
            text: I18n.app-title;
        }
        // Display the "Made with Slint" badge to comply with the
        // Slint Royalty-free license attribution requirement.
        VerticalLayout {
            height: 80px;
            AboutSlint {}
        }
    }
    Button {
        text: I18n.about-btn;
        height: 30px;
        dialog-button-role: action;
        clicked => {
            root.close();
        }
    }
}